### ISSUE TITLE
Medium Priority Updates

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#132]
This issue will catalog any medium priority updates that need to occur in the curriculum. I would not consider these :construction: blockers to :money_with_wings: the course, but they should be addressed in the near term.

**Comment by crichID** [comment]
- [ ] Right now the validation for all items is mostly y/n. In the case of this lab, the user can actually edit a file on the wrong PR and still receive a "correct" notification in the course. @johnpaulashenfelter indicated this is already on the backlog.

![screenshot 2015-09-02 10 57 02](https://cloud.githubusercontent.com/assets/9950121/9635879/830f79dc-5166-11e5-9b42-2671e21ced3c.png)

**Comment by crichID** [comment]
- [x] we recommend that Windows users download and use the bash emulator instead of `CMD.exe` we should update the instructions on [this page](https://learn.wheelhouse.io/events/MMKb2q7HUthUuXUbpZSh/screens/166) accordingly:

![screenshot 2015-09-02 11 30 28](https://cloud.githubusercontent.com/assets/9950121/9635941/d0524bd4-5166-11e5-8284-7969b75d9e41.png)

**Comment by crichID** [comment]
- [ ] the template repo still has the old README. Need to update to remove the reference to desktop applications in GH for Devs. Also remove the instructions as they are duplicates of what is in the course. 

![screenshot 2015-09-02 11 39 07](https://cloud.githubusercontent.com/assets/9950121/9636028/5ffed0c2-5167-11e5-9645-102cbac392f0.png)

**Comment by crichID** [comment]
- [x] git version in graphic is 2.3.2 but in text it is 2.5. We need to update the graphic but I am also hesitant to specify a version because then we have to maintain it. We should give the minimum version based on the activities in the course.

![screenshot 2015-09-02 11 43 15](https://cloud.githubusercontent.com/assets/9950121/9636135/fe298080-5167-11e5-806f-1772e3eec77c.png)

**Comment by crichID** [comment]
- [ ] this image doesn't make sense to me. 

![screenshot 2015-09-02 12 10 09](https://cloud.githubusercontent.com/assets/9950121/9636832/9eafec9e-516b-11e5-8519-8eafddb1b923.png)

**Comment by crichID** [comment]
- [x] Is there a word missing in the first bullet here?

![screenshot 2015-09-02 12 54 09](https://cloud.githubusercontent.com/assets/9950121/9637973/c08c9442-5171-11e5-8a96-4fd38c62d921.png)

**Comment by crichID** [comment]
- [x] we should add the git push-u option to the recap here because it was not covered before and goes by pretty quick in the video

![screenshot 2015-09-02 12 59 33](https://cloud.githubusercontent.com/assets/9950121/9638102/906516bc-5172-11e5-9443-d696ebffc4e7.png)

**Comment by crichID** [comment]
- [x] remove the first sentence here

![screenshot 2015-09-02 13 02 38](https://cloud.githubusercontent.com/assets/9950121/9638153/f04b276a-5172-11e5-91f5-d4dd7c4cab11.png)

**Comment by crichID** [comment]
- [x] add instructions to create the badname.md file

![screenshot 2015-09-02 14 17 09](https://cloud.githubusercontent.com/assets/9950121/9640052/77cc2d10-517d-11e5-81d0-df5134315e56.png)

**Comment by PeterBell** [comment]
Hey @1point618 mind going through these, working on the content ones (getting feedback from @crichID  or myself as required) and hitting up @timlombardo and @johnpaulashenfelter on anything that might require code changes? You're also going to want to @ mention JP on any curriculum PR's. He will then merge them and either import or make updates manually in the db so ensure everything stays in sync but we don't have too many versions of courses floating about.
