### ISSUE TITLE
Lab Issues

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#134]
@johnpaulashenfelter I received feedback from one of our employees as follows:

> I was testing to see what kind of error message/hint would show up if I failed to complete tasks, but instead found that I was able to “Mark Task Completed” without doing anything in my repository, and this is true for all the tasks from section 1 to section 4. (section 5 doesn’t have a lab)

Her username is `muan` - can you please take a look and see if anything strange is happening?

**Comment by 1point618** [comment]
@crichID That is the behavior that we have right now. It's sub-optimal, but until we have better verification built into the app, it's the best we can do. Verification is high on the list of "next fixes" that our PM @timlombardo is putting together, and will be a powerful tool for us education folks to use when building and updating curriculum.

**Comment by crichID** [comment]
@1point618 Ah, I think I misunderstood what she was saying. So could we at least have it show something like "task marked complete manually" instead of showing "correct" for now? Or is that too much to do as a temporary fix?

**Comment by 1point618** [comment]
@timlombardo What do you think, is that an easy copy change or do we need more developer resources for that?

**Comment by timlombardo** [comment]
@crichID @1point618 right now, we don't treat the automated completion or the manual completion differently in the system so, unfortunately, there isn't a quick immediate fix. We all agree it should be improved. Labs are the number one priority for improving the student experience. I plan on including this as part of the upcoming lab verification/validation work.

**Comment by 1point618** [comment]
@timlombardo Why don't the three of us (me, you, and @crichID) get together before finalizing the lab validation "epic", to make sure we're building it as a way to build tools for me and Cynthia.

**Comment by timlombardo** [comment]
:+1: let's do that. We should connect on it once we return from the offsite next week.
