### ISSUE TITLE
Unable to Jump Between Sections using drop down

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#135]
> After I completed the training it would not let me hyperlink back to a previously-viewed module to replay.

@johnpaulashenfelter some customer feedback from Intuit

**Comment by crichID** [comment]
@johnpaulashenfelter can you give me some feedback on the status of this fix?

I am running through the course now. I was in section 2 and able to jump back to section 1, but I cannot jump back to section 2 again.

**Comment by timlombardo** [comment]
@crichID this is next in our backlog behind email confirmation for purchases (which I am going to be sending manually while we finish it) so I'm hoping the fix gets started today or tomorrow.
