### ISSUE TITLE
New Self-paced Classes Set Up

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#136]
@johnpaulashenfelter I'm not sure who I should be sending these requests to. Can someone please set up two self-paced classes as follows:
1. Huawei: this is a customer who is interested in purchasing training and would like to test drive it.
2. "Complimentary class": we have a github superfan who will be teaching some free classes in Africa. We would like to give him access to the course. It would be nice to have an event I can send when I get these types of requests without having a customer name attached.

**Comment by johnpaulashenfelter** [comment]
@crichID How about we just rename the current class here as the Wheelhouse Preview or some such and let anyone use them for now? That way we don't need to worry about spinning up event-by-event for now. 

That will end up mapping where the data's heading for self-serve as well :)

**Comment by crichID** [comment]
@johnpaulashenfelter that is perfect!

**Comment by crichID** [comment]
@johnpaulashenfelter has this been done? I just checked on the event page and it still says Intuit for me!

**Comment by johnpaulashenfelter** [comment]
Its done. Apologies for the delay.

Should I close this now @crichID or wait for you to do it?

**Comment by crichID** [comment]
Perfect! Thank you - closing now!
