### ISSUE TITLE
GH4D: Ecosystem Graphic

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#144]
@1point618 we have a challenge with the ecosystem graphic. Some of the companies you included on the graphic are not officially part of the integration directory yet (see the link on the page) which is also being released at Universe. Can we remove the product names for now?

![screenshot 2015-09-29 12 57 52](https://cloud.githubusercontent.com/assets/9950121/10171864/37c45d04-66aa-11e5-8f6e-6975c5115cdf.png)

**Comment by 1point618** [comment]
I'm sorry @crichID I'm not seeing which companies those are. Did you mean to include a link? Each of the companies on the graphic is listed on this page: https://github.com/integrations

**Comment by crichID** [comment]
@1point618 they may have been listed on the old page, but they are not on the one that will be released at Universe. It may only be staff shipped right now so that may be why you can't see it.

**Comment by PeterBell** [comment]
Hey @crichID do we know which companies we need to remove?

**Comment by crichID** [comment]
@PeterBell if you can't see the page yet then I may not have permission to share that information. I work internally on finding out but I can't guarantee an answer before your deadline so it may be easiest to remove them altogether for now.

**Comment by PeterBell** [comment]
Hi @crichID a couple of comments:
1. Editing the image this late is going to look bad, and having the image without the company names on the image is just going to look weird. How about we just remove the image from the slide and we'll add it at the next content refresh post universe?
2. This brings up a great general issue which is for us to work with you to ship timely training materials, we're going to eventually need a small number of named people who have approved access to staff shipped content. Guessing it's going to be a whole process, but it doesn't make sense for us not to have a couple of people with that access (with the appropriate contractual provisions) so we can help you to build, test and ship content for new features at the same time as the features ship. But let's deal with that post launch!

**Comment by crichID** [comment]
I'm going to go ahead and close this issue down. We are ok with it as-is for now.
