### ISSUE TITLE
User didn't know how to use the app, wants slides explaining it.

### ISSUE THREAD

**Issue by 1point618** [certify/curriculum-github#154]
> I didn't realize I could navigate using the filled dots until I finished the course. It may be worthwhile to use a slide or two to explain how the course site works.

...

> How can I see the table of contents for the course that I'm currently taking? Navigation only has Previous and Next, and when I try 'Back to event home' and then 'Enter course', it takes me back to the current slide. But I want to see the table of contents to revise on the previous section...
> 
> Finally I found it. There is a tiny down triangle next to the title. It's not easy to see!

**Comment by crichID** [comment]
@1point618 where are you pulling the user feedback from? Are you sending a survey?

**Comment by 1point618** [comment]
Some of this is from Intercom, some of it is from a friend of @johnpaulashenfelter's who agreed to take the course and give us feedback on it.

**Comment by PeterBell** [comment]
Hey @crichid this is unsolicited feedback from intercom.io where we're getting ad hoc comments and questions. If you want I could add you so you'd also be able to see comments and respond to qns. Would that be useful? Out of office in an but could get it done early this afternoon - let me know!

**Comment by 1point618** [comment]
@crichID Also for what it's worth, while I'm putting together negative feedback for us here,

**Comment by 1point618** [comment]
@crichID Sorry I hit "close and comment" when trying to delete what I'd written.

My feelings on this feedback are fairly neutral. Some of it is useful, some of it is not. However, I'm trying to take out _all_ actionable feedback and put it here, so that we can discuss which we as a team agree with, and which we think we can let slide. 

I'm sure as things go on we'll find that some people hate X, while others love X. That doesn't mean that we "fix" X as soon as we get the first piece of feedback that someone dislikes it, but that we need to dig into why it is they don't like it. This is just a place to be transparent about what feedback we are getting now.

**Comment by crichID** [comment]
> That doesn't mean that we "fix" X as soon as we get the first piece of feedback that someone dislikes it, but that we need to dig into why it is they don't like it.

@1point618 completely agreed. I was just curious if you guys were sending out a survey of some sort because I was planning to do so.

**Comment by 1point618** [comment]
@crichID No survey yet. If you're planning on doing so, I'm perfectly happy with that. Could we talk about the questions to be asked in the 10am meeting just to make sure all our bases are covered?

**Comment by crichID** [comment]
@1point618 I got a message from @PeterBell that the 10 am meeting was cancelled. I have not created the survey yet so if you have specific questions you would like to ask, please send them over!

**Comment by 1point618** [comment]
I'll start another issue about the survey.

**Comment by PeterBell** [comment]
Hey @crichID @1point618 sorry about me not communicating well about the 10am meeting. Let's circle round elsewhere and find the right frequency and attendees for the right meetings to keep everything aligned and moving forward. I'll get with everyone individually and then propose something . . .
