### ISSUE TITLE
Send Survey to current Wheelhouse free students.

### ISSUE THREAD

**Issue by 1point618** [certify/curriculum-github#156]
@crichID has agreed to take charge of sending out a survey to all our free users.

Here are some questions I'd like to be asked to the students:
1. NPS. "On a scale of 1 to 10, how likely are you to recommend this to a friend?"
2. General demographics. How comfortable they already were with Git and GitHub, what their job is, how technical they are, that kind of thing. 
3. What's your preferred method for learning new software? (multiple answers)
   - Text/Image tutorials
   - Videos
   - Getting a friend to help me
   - Sign up for an offline class
   - Sign up for a MOOC, webinar, or other online class
   - I just jump in and start trying things
4. What did you learn from the course?
5. What do you wish had been further covered?
6. Did anything leave you confused?
7. What did you like or dislike about working on the project on GitHub.

**Comment by crichID** [comment]
@1point618 do you have an easy way to figure out what each screen is based on the number? I would like to know which screens users are stopping on to get a better feel for how to shape the survey! I created a quick pivot table showing the top 10 "last screens":

![screenshot 2015-11-02 10 15 31](https://cloud.githubusercontent.com/assets/9950121/10885336/c2668418-814a-11e5-8892-f1c9a7d50148.png)

**Comment by PeterBell** [comment]
Hi @crichID speaking with @johnpaulashenfelter about this right now. He's working on some code that'd generate a manifest and make it easier to tell things like percentage complete from last screen numbers. It's in the hopper for today to get started, but not sure when this week it'll be completed and shipped . . .

**Comment by 1point618** [comment]
@crichID You can also go to

`https://learn.wheelhouse.io/events/early-access/screens/###`

subbing `###` for the number on the table to see exactly where people are dropping. For instance, 476 is the first page (= people who clicked through but didn't actually do any of the course), 482 is the first video (= people who were turned off by having to watch a video?), 480 is the first slide of the second section, 477 is the second slide, 611 is the last slide of the first section. 620 is the very final slide, so those are the people who clicked through the entire thing.

**Comment by 1point618** [comment]
@crichID I think another good question for the questionnaire would be "Why did you sign up for this course?" I imagine we're going to get a bunch of people who just wanted to see it, and had no learning goals at all.

**Comment by crichID** [comment]
> subbing ### for the number on the table

@1point618 ah thank you! I always forget that trick :stuck_out_tongue_winking_eye:

**Comment by matthewmccullough** [comment]
> I created a quick pivot table showing the top 10 "last screens":

:sparkles:

**Comment by crichID** [comment]
@1point618 @PeterBell I am working on two distinct surveys. One is for users who have not completed the course. The other is for users who have. I have created https://github.com/githubpartners/wheelhouse/pull/49 in the Partner repo so we can collaborate on the content.

**Comment by PeterBell** [comment]
Thanks for that @crichID  - perfect - looking through now. Will respond this pm!

**Comment by PeterBell** [comment]
This has been handled elsewhere and is ready for shipping, so closing down this issue
