### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#172]
Received feedback from customer: 

> I am contacting you because I have found a typo error:
> In "Section 6: Using GitHub Locally", in the 3rd subsection "Cloning a
> Repository: Recap", the last sentence says:
> All edits you make locally _with_ be applied to that branch until you checkout another one. while it should say:
> All edits you make locally _will_ be applied to that branch until you checkout another one.

**Comment by PeterBell** [comment]
Thanks @crichID - @johnpaulashenfelter could you tweak that in the db and @1point618 could you update the curriculum repo?

**Comment by 1point618** [comment]
Fixed.

**Comment by PeterBell** [comment]
Thanks @1point618 !

**Comment by johnpaulashenfelter** [comment]
@1point618 Any chance you can give me a screen number/url? Its complicated to track down otherwise.

**Comment by 1point618** [comment]
@crichid can you? I didn't get the initial feedback so I don't have it. On
phone now.

On Wednesday, November 18, 2015, John Paul Ashenfelter <
notifications@github.com> wrote:

> @1point618 https://github.com/1point618 Any chance you can give me a
> screen number/url? Its complicated to track down otherwise.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wheelhouseio/curriculum-github/issues/172#issuecomment-157839629
> .

## 

Sent from my pocket computer's glass keyboard.

**Comment by 1point618** [comment]
@johnpaulashenfelter did we fix this? If so, let's close it.
