### ISSUE TITLE
Atom causes a lot of issues

### ISSUE THREAD

**Issue by 1point618** [certify/curriculum-github#173]
The no. 1 help request that I get about the content of the course involves Atom. A number of users are unable to get Atom running on the command line, then get stuck when they try to force git commit messages to open in atom. 

@crichID I think we should either include much better instructions on how to use Atom, _or_ give it as an option but use a default system editor like vim in the examples. As it is, we're creating issues for a decent number of people, issues that I can't troubleshoot for them because they're so specific to a user's machine.

**Comment by johnpaulashenfelter** [comment]
vim isn't the default on Windows. Honestly not sure what is -- notepad?

**Comment by 1point618** [comment]
I'm pretty sure we recommend people use https://git-for-windows.github.io/ which comes with BASH emulator. I assume vim comes with that but maybe not.

**Comment by PeterBell** [comment]
With the msysgit on Windows, it does include Vi by default, so that's usually what I recommend. Cool using Atom, but there are definitely install issues. Thoughts @crichID ?

**Comment by crichID** [comment]
@1point618 @PeterBell I suppose we have a few options:
1. Remove the Atom instructions from the config section or more clearly indicate it is optional.
2. Put together a quick help guide on getting Atom set up if they are having problems.
3. Include instructions that if they can't get atom to work they can unset that config option to use the default for their system. 

FWIW, if these are Mac users it is fairly easy to fix (install command line tools). If they are Windows users, we see similar problems with a lot of the text editors (including Notepad++).

**Comment by 1point618** [comment]
I think the issue isn't the "install Atom" instructions, but the fact that all the CLI examples after it assume Atom. That means that if you didn't get it working, and you're new to the CLI, then you're going to be really confused about what to do to continue. I think ideally all the examples should use some sort of default CLI-based text editor, and we can mention after the Atom install instructions, "hey, whenever you see `vim` in the examples feel free to substitute `atom` instead".

We've had both Windows and Mac users IIRC. And for what it's worth, the Mac command line tools haven't worked for some of the Mac users who have had issues with Atom.
