### ISSUE TITLE
User Deleted Repo

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#174]
@johnpaulashenfelter can you please help with the following:

> I was pursuing the early access, on-demand version of the GitHub course. I deleted the tutorial repository that had been set up at my GitHub account by mistake. Is there any way to reset my course progress and to be able to have the repo recreated?
> 
> Repository link: https://github.com/IamAdiSri/github-for-developers-7
> 
> Thanks,
> Aditya Srivastava
> https://github.com/IamAdiSri

**Comment by johnpaulashenfelter** [comment]
@crichID done.

**Comment by crichID** [comment]
@johnpaulashenfelter thank you! Learner has been notified.
