### ISSUE TITLE
Pronunciation of "git".

### ISSUE THREAD

**Issue by 1point618** [certify/curriculum-github#175]
Sounds like one of our British users is picking up variations in the way that our narrator is saying the word "git". In my dialect of American English at least, the variations are all non-phonemic but are definitely there. This British user, however, hears the variations as different phonemes so keeps hearing our narrator saying "get". 

> https://www.youtube.com/watch?v=gRAMYnQcA_s The reader on this video is reading his script wrong.  
> He says: "GET branch"  
> the correct way to say it should be "GIT branch"
## 

> https://www.youtube.com/watch?v=SPNodd0M4wA he still carries on saying "GET status" and "GET add ." in this video as well. Sounds lame.
## 

> https://www.youtube.com/watch?v=6w8_Z1nd9_s maybe i am just hearing it wrong, but the guys still carrys on saying GET instead of GIT and now i think i am hearing him say GETHUB :/

**Comment by crichID** [comment]
@1point618 I sent the user an email and told him they are pronounced essentially the same in US English. I asked him to send me a recording of how he says GIT. However, I am not inclined to re-record and replace these videos based on a difference in dialect!

**Comment by 1point618** [comment]
Ah. If you reply on Intercom, it will email them if they're not online. That way we're not getting our wires crossed.
