### ISSUE TITLE
Instruction Inconsistency in Section 7 & 8 - Users on Wrong Branch

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#176]
### Feedback from learner:

In "Section 8: Working with Local Files", in the assignment subsection
"Modifying Local Files", you do not mention to do this in the feature
branch (as previously suggested in the videos). Therefore, I think most of
the people will perform this staging and committing in the master branch. I
think so, because in the previous assignment (subsection "Pulling Changes"
in the "Section 7: The Workflow End-to-End"), people are asked to checkout
to the master branch to retrieve the changes from the remote. Therefore,
they would be already in the master branch.

If people perform the staging and commit in the master branch, then they
will not be able to perform a subsequent assignment. The assignment
""Merging Local Changes" (also in "Section 8: Working with Local Files")
asks to merge the local feature branch into the master one. And this can
only be done if previous staging and committing has been done in the
feature branch.

**Comment by 1point618** [comment]
Great point! This should definitely go on the list of things to change.
