### ISSUE TITLE
YouTube inaccessible from China

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#177]
I was just looking through some of the survey results and I saw this response from one learner:

> youtube cannot be accessed from China mainland

@loranallensmith any advice here?

**Comment by loranallensmith** [comment]
@crichID This is quite a pickle.  I did some research last night and it looks like both YouTube and Vimeo are blocked at least part, if not all, of the time in mainland China.  I hadn't thought of this when we were choosing a video platform in #70.

I'm wondering if hosting these videos somewhere outside of Wheelhouse and then embedding them as HTML5 videos would be an option.  Not sure about all the moving parts or what bandwidth concerns we'd need to address though.

**Comment by matthewmccullough** [comment]
# typed-on-mobile-so-no-cross-links-yet

There was a Halp thread recently where I called in legal review where a Chinese developer asked to host the videos we have on YouTube on his own site so Chinese devs could access them.  We could potentially ask him to host more videos.

**Comment by PeterBell** [comment]
Going to cc @johnpaulashenfelter - we're happy to have the video hosted anywhere that makes sense to you - just want to make sure he's in the loop so we can assess the engineering effort that might be required.

**Comment by loranallensmith** [comment]
> a Chinese developer asked to host the videos we have on YouTube on his own site so Chinese devs could access them. We could potentially ask him to host more videos.

@matthewmccullough thanks for the historical reference there.  This might be a viable option since someone has already floated an offer to host them.

Revisiting my earlier recommendation:

> hosting these videos somewhere outside of Wheelhouse and then embedding them as HTML5 videos

If we were to self-host, we'd lose out on some pretty valuable viewership metrics from YouTube.  I believe that was one of the big reasons we went that direction.  I :heart: @crichID's point in #178 that video transcripts might help address this need.

How do others feel?  From a pedagogical, engineering, or business standpoint — could transcripts be the most viable way to address this need right now?

**Comment by johnpaulashenfelter** [comment]
Transcripts were the absolutely most helpful things we did with videos at Treehouse. Not only did it route around video issues, many ESL folks could _read_ the transcript slowly and understand it but not understand the video at all in real-time. I find the same is true for me for Spanish.

We used a third-party video transcription service -- Cielo i think, it's been a while :smile: 

Plus once its transcribed, then it can be _translated_.

In this day and age do you run into (enterprise) customers that have blocked Youtube, etc for "security" reasons?

Short-term, transcription is my recommendation over trying to route around the GreatFirewall of China.
