### ISSUE TITLE
Updates to Curriculum

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#188]
@1point618 @johnpaulashenfelter @PeterBell we have a list of modules we would like to add to the curriculum. As we do, I am wondering if it also makes sense to move towards the article format (especially since we are showing it in the demo course). 

I can make the module changes but I am unsure what this will mean from your end since there is no direct import. Can you please advise on the process we will need to follow and the timeframe for applying the changes on your end?

**Comment by PeterBell** [comment]
Hi @crichID thanks for reaching out - will let @1point618 lead. We may need to cover details in call Jan 4th. Main issues are going to be around how this impacts students who are already in the course and what it means to them when the course changes. Going to re cc @johnpaulashenfelter as we'll need him involved in the discussion!

**Comment by 1point618** [comment]
@crichID Let's schedule a call for the new year about this. 

Generally, +1 to article format, and I'll coordinate with @johnpaulashenfelter on the technical specifics. Short answer is that we're going to do another import of the course before we begin selling it to enterprises fixing all the problems encountered in the beta test, so it would be great if we could include this in that update. There is no set timeframe on that yet, at minimum we'd need you to :OK: the changes made. We can discuss that on the phone call. 

Ideally, we'd break up the current course + the new modules into several smaller courses, but I'm open to discussion on how/whether to do that based on the new content that you would like to add.
