### ISSUE TITLE
Customer Feedback: Needs Improvement

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#189]
@1point618 just passing this along. I am not inclined to make any changes based on the feedback here. If you agree, please close this issue after you have reviewed:

> First, the /bios/ directory doesn't exist when we first join the class So, in order to add a bio we have to type in the directory first, then specify the filename This action creates the /bios/ subdirectory

This is actually shown in the video so the student is sorta telling on himself that he skipped the videos.

> Second, the last task of creating content on my desktop failed to commit, because it kept saying I had uncommitted changes that needed to be applied What were those changes, you might ask? They were related to a /Bios/ subdirectory that no longer existed

I would guess he deleted the bios subdirectory but was trying to use `git add .` to commit it instead of `git add -A`. Not sure why he would delete the bios subdirectory as he is not instructed to do so in the course but we don't really have a way to mitigate these types of scenarios at this time.

> I was unable to Cancel or Discard the changes using the GitHub desktop, resulting in an endless loop of error messages and the inability to commit my locally created file to the class repository
> 
> So I'll probably take what I know now and "redo" the class with a fresh repository / desktop environment

**Comment by 1point618** [comment]
@crichID I did see this, and completely agree that it's not actionable. There's also the issue that he's using GitHub Desktop instead of the command line, which is just not something that we support.
