### ISSUE TITLE
Created three different repositories automatically

### ISSUE THREAD

**Issue by rajasiman** [certify/curriculum-github#190]
Hey guys,

I would like to convey my gratitude to you all for this wonderful course. I signed up for this during early access and completed the course an hour ago. I noticed something strange that happened and I'm not sure if it was intended? 

I signed up for this on 17 Dec 2015, completed the first section(a new repository, **github-for-developers-7**, was created at this time). I had something else come up and so I didn't continue the course until yesterday. I picked up where I left off and within sometime, I got a notification that a new repository(**github-for-developers-8**) was created in my account for this course. I continued to work on the exercises and then about 2 hours later, I got another notification that a new repository(**github-for-developers-9**) has been created. 

I also noticed that two new courses were added to my account at https://learn.wheelhouse.io/events
![image](https://cloud.githubusercontent.com/assets/5812541/12197109/3590a5b8-b62a-11e5-9aee-4bff99cf2cee.png)

The initial course URL(4th in the image): https://learn.wheelhouse.io/events/early-access
Course URL when I logged in yesterday(3rd in the image): https://learn.wheelhouse.io/events/ea
Third course URL which I completed today(2nd in the image): https://learn.wheelhouse.io/events/cCCfdunbJh_jH-7EURtB

Also notice the company contact information is different on two of the links and one of them doesn't have any info at all. Really not sure if the time period between the signup and completion caused this.

---

A small question, The soundtrack in the background of the videos was extremely calming. Can I know  the name of the track?

**Comment by johnpaulashenfelter** [comment]
@rajasiman Each of those courses is a slightly different version -- we use the events/SOME_URL to differentiate them. In most cases, there's one event per course for free courses but a few of them are in the wild -- earlyaccess and ea to be specific -- for GitHub for Developers. Its also why the repos were created -- one per course/event so we can link webhooks correctly.

The event with the random-ish URL is a purchased one.

Progress is going to be tracked individually for each event, though some of the activities from the /ea and /early-access course will overlap a bit in your course progress thanks to some historical quirks.

Glad you enjoyed the course!
