### ISSUE TITLE
Create page type for non-verified labs

### ISSUE THREAD

**Issue by crichID** [certify/curriculum-github#25]
Per discussion in #14 and based on several other modules, we will need to have a page that looks similar to a lab but can take un-verified tasks. As learners progress through the course, there are many hands on activities that will be completed locally that cannot be verified. We still need a way to give learners these instructions.

**Comment by PeterBell** [comment]
We have a structure for this. If you could put in real content into at least one lab and let me know and I'll merge it in and see how the import goes

**Comment by PeterBell** [comment]
Gonna close this - we now have these in the yaml. If there are bugs or issues in import or display @iwz will fix them :)
