### ISSUE TITLE
Images required

### ISSUE THREAD

**Issue by PeterBell** [certify/curriculum-github#49]
Hey @crichID could you work with the team to start to replace the placeholder image we're currently using for most of the slides with real images? Obviously it isn't required to start getting feedback, but I'd love to make this as realistic as possible ASAP so we can really start to dig into the full end user experience and open this up to some non-GitHub beta-users over the next week or two.

**Comment by crichID** [comment]
Very happy to close this bad boy out! Now we just need videos
