### ISSUE TITLE
Video Content Details

### ISSUE THREAD

**Issue by loranallensmith** [certify/curriculum-github#70]
As we ready ourselves to add our video content to these modules, I had a few questions I've been wrestling with.
### Synchronizing Content

I am wondering if we need to have a system in place for updating video content to match any changes to the curriculum.  @PeterBell and @crichID, do either of you anticipate changes to the narration in the modules that will require the video content to be updated? I ask because it takes a bit longer to update video content.  Not sure how much room we have for the video to deviate from the Do/Say blocks. :confused:  After chatting with Cynthia about wording the other day, it sounds like there is some wiggle room though.
### Where to Put Files

I noticed that the modules currently pull from YouTube for their content.  Is that the route we should go for getting video into Certify, or will these videos live in the repository somewhere?  I can tweak the export settings depending on where the videos will eventually reside.

**Comment by PeterBell** [comment]
Hey @loranallensmith I'll leave the first question to @crichID although I'm guessing the text (and video) will have to change every so often (less as we 'burn in' the content).

Right now the videos pull from either vimeo or youtube. Open to anything sane. Reluctant to get into video hosting business unless there's a compelling reason so I'd suggest a vimeo pro account for the olayer and analytics and youtube where you want to use it for marketing to get traffic, but we are at your beck and call on this stuff, so if you'd like us to do something different, let me know and we'll figure it out!

**Comment by crichID** [comment]
> do either of you anticipate changes to the narration in the modules that will require the video content to be updated?

@loranallensmith I have a mess of changes to push based on today's call, but after that I think we need to limit changes to only those things that are wrong. Having your :eyes: on the scripts as you record them will help with this quite a bit. 

That said, I am going to mark CONT-01 - CONT -035 as "do not change unless absolutely necessary" from this point on and will continue to do the same for videos as you get them wrapped up. I know that editing video is not as easy as editing the .yaml file and I want to avoid churning to the extent possible.

**Comment by loranallensmith** [comment]
@crichID Sounds good!  I'm definitely :cool: with making changes as we continue to shape the curriculum, so please don't feel pressured to lock anything down just for the videos. :smiley_cat:  I will  keep my :eyes: peeled for things as I review the scripts when recording too. :+1: 

> Reluctant to get into video hosting business

For sure @PeterBell!  I think Vimeo and YouTube are the way to go.  I really :heart: the idea of getting those analytics about these videos so we can see how students are viewing them.

Will we need to protect these videos in any way @crichID?  Should they be available to the general public or just to students from within Certify?

**Comment by crichID** [comment]
> Will we need to protect these videos in any way @crichID? Should they be available to the general public or just to students from within Certify?

@loranallensmith I am torn. Part of me wants to limit them to students inside Certify, the other parts says it won't hurt anything if someone is searching for creating branches and stumbles on a curriculum video. Maybe we can touch base about this on Monday. I am all about reusability of these and would like to hear your thoughts as well.

**Comment by loranallensmith** [comment]
### Following up on a :jeans: chat with @crichID today:

It sounds like the plan is to keep the video content locked down for now -- insofar as much as YouTube and Vimeo will support.  If we want to open them up to the general public later on, both sites give us the ability to do this with relative ease.

If we are hosting the videos on YouTube, we can classify them as "unlisted" so they're still embeddable but hidden from search results.  Vimeo gives us a bit more control by letting us specify particular domains where the videos can be embedded.

The embedded Vimeo interface has always seemed a bit more polished to me, but I :heart: the amount of detail in the analytics for our YouTube channel.  @PeterBell will Certify provide data about our students that we can analyze for attendance patterns, demographics, performance, etc.?  I imagine it might; apologies as I'm definitely showing my ignorance of the system here. :bow:

**Comment by matthewmccullough** [comment]
Related: https://github.com/github/training-team/issues/961 (four topic rotation)

I see the value as:

- Customer get used to the rhythm and are better able to join or book the time (like our monthly open enrollment)
- Anytime we can help make something more rhythmic, it leaves more creative brain power for the content
- These review classes continue to be great sources of 1. topic explorations 2. presentation practice 3. recordings

**Comment by matthewmccullough** [comment]
My observations:
- YouTube analytics are much better
- Vimeo has a better embed
- YouTube is more likely than Vimeo to be blocked at some companies and universities, but only by a little bit
- I would never put a customer-private class video on YouTube (I think we all agree on this) and the one-password approach to Vimeo sharing
- No harm if folks "accidentally" watch or discover the unlisted curriculum videos on YouTube - thought it is probably boring to watch them outside of the context of the curriculum.
- We could eventually create a strategy of using these micro-videos as something we wanted others to embed in their own blog posts (and then the end-cards on the video could lead people to our other offerings)

**Comment by loranallensmith** [comment]
Thanks for everyone's input on this.  It sounds like YouTube is the way to go for now -- the value of the analytics outweigh the slickness of Vimeo's embed.  We'd just need to be sure to keep the curriculum videos unlisted for now.  Even if the videos aren't as interesting out of context, I'd still hate for customers to feel like we might be charging them for something that's freely available.  This strategy sets us up for potential partnerships with other teams who want to embed the content.  They'd use the same embed link and we could even track which sources are getting the most views.

Going to close this Issue out since we're in a good place to move forward.  I will work on getting any :ship:ed videos in `github/services` uploaded to YouTube so we can start PR-ing the links into the curriculum modules. :grinning:
