### ISSUE TITLE
Admin access to Certify

### ISSUE THREAD

**Issue by loranallensmith** [certify/curriculum-github#78]
Hey @PeterBell!  

Apologies, as I missed the :boat: when everyone was getting added.  I believe my account is still set up as a general user or student in Certify.  Would it be possible for me to be promoted to an admin?

**Comment by PeterBell** [comment]
Just made you an admin @loranallensmith :smile:

**Comment by loranallensmith** [comment]
Woo!  I'm in. :tada:  Thanks a bunch, @PeterBell! :metal:
